server:
  port: 10040
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://101.32.46.56/putao
    username: root
    password: LoveJava17*
#  redis:
#    host: 101.32.46.56
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9090/eureka
#  instance:
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.putao.item.pojo