server:
  port: 9090
spring:
  application:
    name: putao-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9090/eureka
    register-with-eureka: false
    fetch-registry: false
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 20000