server:
  port: 10050
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 1MB
#eureka:
#  client:
#    service-url:
#      defaultZone: http://101.32.46.56/eureka
#  instance:
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 15
fdfs:
  so-timeout: 15001  #读取超时时间
  connect-timeout: 10001  #连接超时时间
  thumb-image:  #缩略图
    width: 60
    height: 60
  tracker-list: #tracker地址
    - 101.32.46.56:22122