server:
  port: 10010
spring:
  application:
    name: putao-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9090/eureka
#    registry-fetch-interval-seconds: 30
zuul:
  prefix: /api
  routes:
    item-service: /item/** #路由到candy的微服务
    user-service: /user/** #路由到用户微服务
    auth-service: /auth/**
  add-host-header: true
  sensitive-headers:  # 覆盖默认敏感头信息
  host:
    connect-timeout-millis:  15000
    socket-timeout-millis: 12000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

