server:
  port: 10010
spring:
  application:
    name: putao-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api
  routes:
    item-service: /item/** #路由到candy的微服务
    user-service: /user/** #路由到用户微服务
    auth-service: /auth/**
  add-host-header: true
  sensitive-headers:  # 覆盖默认敏感头信息
