server:
  port: 10030
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9090/eureka
#    registry-fetch-interval-seconds: 30
#  instance:
#    lease-renewal-interval-in-seconds: 30
#    lease-expiration-duration-in-seconds: 90
putao:
  jwt:
    secret: putao4zhendenanchi!!! # 登录校验的密钥
    pubKeyPath: C:\\tmp\\rsa\\rsa.pub # 公钥地址
    priKeyPath: C:\\tmp\\rsa\\rsa.pri # 私钥地址
    expire: 10080 # 过期时间,单位分钟
    cookieName: PT_TOKEN