server:
  port: 10020
  servlet:
    context-path: /shfhfdhj
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://101.32.46.56:3306/putao
    username: root
    password: LoveJava17*
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      host: 101.32.46.56
      database: comment
  redis:
    host: 101.32.46.56
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9090/eureka
#  instance:
#    lease-renewal-interval-in-seconds: 30
#    lease-expiration-duration-in-seconds: 90
mybatis:
  type-aliases-package: com.putao.user.pojo